# Use postgres/example user/password credentials
version: '3.1'

services:
 postgres:
         image: "postgres:latest"
         container_name: app-postgres
         restart: always
         ports:
             - "5434:5432"
         environment:
             - POSTGRES_PASSWORD=postgres
             - POSTGRES_USER=myuser
             - POSTGRESS_DB=mydb
