import Notification from '@/components/Notification'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Fotter from '@/components/Fotter'
import AuthProvider from '@/components/AuthProvider'
import QueryProvider from '@/components/QueryProvider'
import { ToastContainer } from 'react-toastify'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Karsh Restaurant',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <QueryProvider>
            
        <Notification/>
        <Navbar/>
        {children}
        <Fotter/>
        <ToastContainer position='bottom-right' theme='dark' autoClose={3000}/>
        </QueryProvider>

        </AuthProvider>
        </body>
    </html>
  )
}
